### ISSUE TITLE
Can not view the chart inline in jupyter notebook

### ISSUE THREAD

**Issue by dove88** [altair-viz/altair-tutorial#13]
Hi, 
I opened your 'maps' notebook, I can't view the plot inline in this notebook. I just got blank output for your info please.

I attached the screen shot

Thanks
![Screenshot_2022_0422_142551](https://user-images.githubusercontent.com/85496354/164672624-684e2d8f-d593-4870-9163-3c84451c85f2.png)

**Comment by jakevdp** [comment]
Hi - this is a github issue. Github's notebook viewer does not allow execution of javascript within notebooks for security reasons, and Altair charts are rendered with Javascript. There's nothing we can really do about that on our end. I'd recommend either downloading the notebooks and viewing them with JupyterLab locally, or using a service like http://nbviewer.jupyter.org which does not remove javascript artifacts from its renderings.

**Comment by dove88** [comment]
I have the same issue with jupyter notebook too.
I have created a new thred about displaying Altair chart inline in jupyter notebook.
Still conversation is going on there?
Just I get a blank output while I render the chunk of code.

**Comment by jakevdp** [comment]
Yes, I saw that thread. It's a different issue than the one you raise here.

**Comment by jakevdp** [comment]
In that case it seems to be something about your local browser's security configuration. I'm not sure how to fix it given the information you provided.

**Comment by dove88** [comment]
> Yes, I saw that thread. It's a different issue than the one you raise here.

I do understand, I was under impression that the issue that I am facing might be same as with this too.
Thank you for the reply.
However I can work with jupyter lab with mimetype renderer. Good luck
